name: Pyrocell
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - pytorch::pytorch
  - torchvision
  - torchaudio
  - pyro-ppl
  - ca-certificates
  - certifi
  - openssl
  - numpy
  - matplotlib
  - jupyter
  - pandas
  - pdoc
  - tensorflow
  - tensorflow-probability
  - gpflow
